#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=12:00:00
#PBS -N app-visual-white-matter
#PBS -V

set -xe

analysis_pipeline=`jq -r '.analysis' config.json`

# need to build out rest of potential analysis pipelines
if [[ ${analysis_pipeline} == "polarAngleMeridiansConnectomics" ]]; then
    [ ! -f ./src/connectomics/config.json ] && cp config.json ./src/connectomics/
    . ./src/connectomics/main
fi
