#!/bin/bash

# connectomics: main file

## parcellation generator
# . ./src/connectomics/parcellation-generator-main.sh

# ## segment tracts
# . ./src/connectomics/tract-segmentation-main.sh

# ## scmrt connectivity
# . ./src/connectomics/scmrt-connectivity-main.sh 

# ## network generator
# . ./src/connectomics/network-generator-main.sh

# ## network measurements
# . ./src/connectomics/network-measurements-main.sh

# ## create cortexmap datatype
# . ./src/connectomics/cortexmap-generator-main.sh

## create wmc datatype
. ./src/connectomics/wmc-generator-main.sh

## clean up
# [ ! -d tracts ] && mkdir tracts && mv *.tck ./tracts/
# mv *.nii.gz *.mif c_ras.mat *.txt *.pial ./raw/
# mv *.func.gii ./cortexmap/cortexmap/func/