#!/bin/bash

# connectomics: main file

## parcellation generator
. ./src/connectomics/parcellation-generator-main.sh

## segment tracts
. ./src/connectomics/tract-segmentation-main.sh

## scmrt connectivity
. ./src/connectomics/scmrt-connectivity-main.sh 

## network generator
. ./src/connectomics/network-generator-main.sh

## network measurements
. ./src/connectomics/network-measurements-main.sh

## create cortexmap datatype
. ./src/connectomics/cortexmap-generator-main.sh

## create wmc datatype
. ./src/connectomics/wmc-generator-main.sh

## create network statistics csvs
. ./src/connectomics/netstats-generator-main.sh

## clean up
[ ! -d tracts ] && mkdir tracts tracts/tcks && mv *.tck ./tracts/tcks/
mv *.nii.gz *.mif c_ras.mat *.txt *.pial ./metric ./raw/
mv *.func.gii ./cortexmap/cortexmap/func/